# Generated by Django 4.0.3 on 2022-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriouscategory',
            options={'verbose_name': 'Категория важности', 'verbose_name_plural': 'Категории важности'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
    ]
